/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji"

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    "legal-pages": LegalPage
    "blog-authors": BlogAuthor
    "blog-categories": BlogCategory
    "blog-tags": BlogTag
    "blog-posts": BlogPost
    "email-templates": EmailTemplate
    "payload-kv": PayloadKv
    "payload-jobs": PayloadJob
    "payload-locked-documents": PayloadLockedDocument
    "payload-preferences": PayloadPreference
    "payload-migrations": PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    "legal-pages": LegalPagesSelect<false> | LegalPagesSelect<true>
    "blog-authors": BlogAuthorsSelect<false> | BlogAuthorsSelect<true>
    "blog-categories": BlogCategoriesSelect<false> | BlogCategoriesSelect<true>
    "blog-tags": BlogTagsSelect<false> | BlogTagsSelect<true>
    "blog-posts": BlogPostsSelect<false> | BlogPostsSelect<true>
    "email-templates": EmailTemplatesSelect<false> | EmailTemplatesSelect<true>
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>
    "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>
    "payload-locked-documents":
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    "payload-preferences":
      | PayloadPreferencesSelect<false>
      | PayloadPreferencesSelect<true>
    "payload-migrations":
      | PayloadMigrationsSelect<false>
      | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  fallbackLocale: null
  globals: {
    "site-settings": SiteSetting
    "blog-settings": BlogSetting
    "home-page": HomePage
    "faq-page": FaqPage
  }
  globalsSelect: {
    "site-settings": SiteSettingsSelect<false> | SiteSettingsSelect<true>
    "blog-settings": BlogSettingsSelect<false> | BlogSettingsSelect<true>
    "home-page": HomePageSelect<false> | HomePageSelect<true>
    "faq-page": FaqPageSelect<false> | FaqPageSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish
      inline: {
        input: unknown
        output: unknown
      }
    }
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  name: string
  role: "editor" | "admin"
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: "users"
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number
  alt: string
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number
  title: string
  slug: string
  summary?: string | null
  body?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ("ltr" | "rtl") | null
      format: "left" | "start" | "center" | "right" | "end" | "justify" | ""
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  seoTitle?: string | null
  seoDescription?: string | null
  updatedAt: string
  createdAt: string
  _status?: ("draft" | "published") | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors".
 */
export interface BlogAuthor {
  id: number
  name: string
  slug: string
  bio?: string | null
  avatar?: (number | null) | Media
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number
  name: string
  slug: string
  description?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags".
 */
export interface BlogTag {
  id: number
  name: string
  slug: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number
  title: string
  slug: string
  excerpt: string
  coverImage: number | Media
  ogImage?: (number | null) | Media
  body: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ("ltr" | "rtl") | null
      format: "left" | "start" | "center" | "right" | "end" | "justify" | ""
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  author: number | BlogAuthor
  categories?: (number | BlogCategory)[] | null
  tags?: (number | BlogTag)[] | null
  publishAt: string
  isFeatured?: boolean | null
  seoTitle?: string | null
  seoDescription?: string | null
  updatedAt: string
  createdAt: string
  _status?: ("draft" | "published") | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number
  key: string
  subjectTemplate: string
  htmlTemplate: string
  textTemplate?: string | null
  isActive: boolean
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  taskStatus?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  completedAt?: string | null
  totalTried?: number | null
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string
        completedAt: string
        taskSlug: "inline" | "schedulePublish"
        taskID: string
        input?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        output?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        state: "failed" | "succeeded"
        error?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        id?: string | null
      }[]
    | null
  taskSlug?: ("inline" | "schedulePublish") | null
  queue?: string | null
  waitUntil?: string | null
  processing?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: "users"
        value: number | User
      } | null)
    | ({
        relationTo: "media"
        value: number | Media
      } | null)
    | ({
        relationTo: "legal-pages"
        value: number | LegalPage
      } | null)
    | ({
        relationTo: "blog-authors"
        value: number | BlogAuthor
      } | null)
    | ({
        relationTo: "blog-categories"
        value: number | BlogCategory
      } | null)
    | ({
        relationTo: "blog-tags"
        value: number | BlogTag
      } | null)
    | ({
        relationTo: "blog-posts"
        value: number | BlogPost
      } | null)
    | ({
        relationTo: "email-templates"
        value: number | EmailTemplate
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: "users"
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: "users"
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T
  role?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  summary?: T
  body?: T
  seoTitle?: T
  seoDescription?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-authors_select".
 */
export interface BlogAuthorsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  bio?: T
  avatar?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  description?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags_select".
 */
export interface BlogTagsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  excerpt?: T
  coverImage?: T
  ogImage?: T
  body?: T
  author?: T
  categories?: T
  tags?: T
  publishAt?: T
  isFeatured?: T
  seoTitle?: T
  seoDescription?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  key?: T
  subjectTemplate?: T
  htmlTemplate?: T
  textTemplate?: T
  isActive?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T
  taskStatus?: T
  completedAt?: T
  totalTried?: T
  hasError?: T
  error?: T
  log?:
    | T
    | {
        executedAt?: T
        completedAt?: T
        taskSlug?: T
        taskID?: T
        input?: T
        output?: T
        state?: T
        error?: T
        id?: T
      }
  taskSlug?: T
  queue?: T
  waitUntil?: T
  processing?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number
  brandName?: string | null
  headerLinks?:
    | {
        label: string
        href: string
        id?: string | null
      }[]
    | null
  footerLinks?:
    | {
        label: string
        href: string
        id?: string | null
      }[]
    | null
  footer?: {
    tagline?: string | null
    copyrightText?: string | null
    statusText?: string | null
    columns?:
      | {
          title: string
          links?:
            | {
                label: string
                href: string
                id?: string | null
              }[]
            | null
          id?: string | null
        }[]
      | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-settings".
 */
export interface BlogSetting {
  id: number
  heroTitle: string
  heroDescription?: string | null
  defaultOgImage?: (number | null) | Media
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number
  title: string
  summary?: string | null
  hero?: {
    badge?: string | null
    headline?: string | null
    description?: string | null
    primaryCtaLabel?: string | null
    secondaryCtaLabel?: string | null
    trustLine?: string | null
  }
  valueProps?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  valuePropsSection?: {
    eyebrow?: string | null
    headline?: string | null
  }
  journeySection?: {
    eyebrow?: string | null
    headline?: string | null
    description?: string | null
    steps?:
      | {
          title: string
          description?: string | null
          details?: string | null
          id?: string | null
        }[]
      | null
  }
  sections?: {
    featuredPlansTitle?: string | null
    featuredPlansDescription?: string | null
    planGroupsTitle?: string | null
    planLocationsTitle?: string | null
    comparisonTitle?: string | null
    comparisonDescription?: string | null
  }
  locationSection?: {
    eyebrow?: string | null
    headline?: string | null
    description?: string | null
    footerTitle?: string | null
    footerDescription?: string | null
    ctaLabel?: string | null
  }
  testimonialsSection?: {
    eyebrow?: string | null
    headline?: string | null
    ratingLabel?: string | null
    items?:
      | {
          quote?: string | null
          name?: string | null
          role?: string | null
          id?: string | null
        }[]
      | null
  }
  faqPreviewSection?: {
    eyebrow?: string | null
    headline?: string | null
    description?: string | null
    ctaLabel?: string | null
    items?:
      | {
          question?: string | null
          answer?: string | null
          id?: string | null
        }[]
      | null
  }
  liveSupportSection?: {
    eyebrow?: string | null
    headline?: string | null
    description?: string | null
    topics?:
      | {
          title: string
          description?: string | null
          id?: string | null
        }[]
      | null
  }
  finalCta?: {
    headline?: string | null
    description?: string | null
    primaryCtaLabel?: string | null
    secondaryCtaLabel?: string | null
  }
  seoTitle?: string | null
  seoDescription?: string | null
  _status?: ("draft" | "published") | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number
  title: string
  summary?: string | null
  items?:
    | {
        question: string
        answer: string
        id?: string | null
      }[]
    | null
  seoTitle?: string | null
  seoDescription?: string | null
  _status?: ("draft" | "published") | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T
  headerLinks?:
    | T
    | {
        label?: T
        href?: T
        id?: T
      }
  footerLinks?:
    | T
    | {
        label?: T
        href?: T
        id?: T
      }
  footer?:
    | T
    | {
        tagline?: T
        copyrightText?: T
        statusText?: T
        columns?:
          | T
          | {
              title?: T
              links?:
                | T
                | {
                    label?: T
                    href?: T
                    id?: T
                  }
              id?: T
            }
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-settings_select".
 */
export interface BlogSettingsSelect<T extends boolean = true> {
  heroTitle?: T
  heroDescription?: T
  defaultOgImage?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T
  summary?: T
  hero?:
    | T
    | {
        badge?: T
        headline?: T
        description?: T
        primaryCtaLabel?: T
        secondaryCtaLabel?: T
        trustLine?: T
      }
  valueProps?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  valuePropsSection?:
    | T
    | {
        eyebrow?: T
        headline?: T
      }
  journeySection?:
    | T
    | {
        eyebrow?: T
        headline?: T
        description?: T
        steps?:
          | T
          | {
              title?: T
              description?: T
              details?: T
              id?: T
            }
      }
  sections?:
    | T
    | {
        featuredPlansTitle?: T
        featuredPlansDescription?: T
        planGroupsTitle?: T
        planLocationsTitle?: T
        comparisonTitle?: T
        comparisonDescription?: T
      }
  locationSection?:
    | T
    | {
        eyebrow?: T
        headline?: T
        description?: T
        footerTitle?: T
        footerDescription?: T
        ctaLabel?: T
      }
  testimonialsSection?:
    | T
    | {
        eyebrow?: T
        headline?: T
        ratingLabel?: T
        items?:
          | T
          | {
              quote?: T
              name?: T
              role?: T
              id?: T
            }
      }
  faqPreviewSection?:
    | T
    | {
        eyebrow?: T
        headline?: T
        description?: T
        ctaLabel?: T
        items?:
          | T
          | {
              question?: T
              answer?: T
              id?: T
            }
      }
  liveSupportSection?:
    | T
    | {
        eyebrow?: T
        headline?: T
        description?: T
        topics?:
          | T
          | {
              title?: T
              description?: T
              id?: T
            }
      }
  finalCta?:
    | T
    | {
        headline?: T
        description?: T
        primaryCtaLabel?: T
        secondaryCtaLabel?: T
      }
  seoTitle?: T
  seoDescription?: T
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  title?: T
  summary?: T
  items?:
    | T
    | {
        question?: T
        answer?: T
        id?: T
      }
  seoTitle?: T
  seoDescription?: T
  _status?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: "full"
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ("publish" | "unpublish") | null
    locale?: string | null
    doc?: {
      relationTo: "blog-posts"
      value: number | BlogPost
    } | null
    global?: string | null
    user?: (number | null) | User
  }
  output?: unknown
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
